export const TOGGLE_TODO_CHECKED_STARTED = 'TODO/TOGGLE_CHECKED_STARTED';
export const TOGGLE_TODO_CHECKED_SUCCESS = 'TODO/TOGGLE_CHECKED_SUCCESS';
export const TOGGLE_TODO_CHECKED_FAILURE = 'TODO/TOGGLE_CHECKED_FALIURE';

