// counter of actionTypes 
export const INCREMENT = 'DEMO/COUNTER/INCREMENT'
export const INCREMENT_IF_ODD = 'DEMO/COUNTER/INCREMENT_IF_ODD'
export const DECREMENT = 'DEMO/COUNTER/DECREMENT'
export const INCREMENT_ASYNC = 'DEMO/COUNTER/INCREMENT_ASYNC'
export const DECREMENT_ASYNC = 'DEMO/COUNTER/DECREMENT_ASYNC'

// users of actionTypes
export const GET_USERS = 'DEMO/USERS/GET_USERS'
export const GET_USERS_SUCCESS = 'DEMO/USERS/GET_USERS_SUCCESS'
export const GET_USERS_FAILURE = 'DEMO/USERS/GET_USERS_FAILURE'
