export const FETCH_USERS = 'DEMO/USERS/FETCH_USERS'
export const FETCH_USERS_LOADING = 'DEMO/USERS/FETCH_USERS_LOADING'
export const FETCH_USERS_SUCCESS = 'DEMO/USERS/FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILURE = 'DEMO/USERS/FETCH_USERS_FAILURE'
