export const TOGGLE_SIDER_VISIBLE = 'SIDER/TOGGLE_VISIBLE'
export const TOGGLE_USERBOX_VISIBLE = 'HOME/SIDER/USERBOX/TOGGLE_VISIBLE'
export const TOGGLE_MOREBOX_VISIBLE = 'HOME/CONTENT/TOOLBAR/MOREBOX/TOGGLE_VISIBLE'
