export const GETDATA_STARTED = 'GETDATA/STARTED';
export const GETDATA_SUCCESS = 'GETDATA/SUCCESS';
export const GETDATA_FAILURE = 'GETDATA/FAILURE';
export const UPDATE_DATA_CHECKED_STATUS = 'DATA/UPDATE_CHECKED_STATUS';
export const SELECT_TODO = 'TODO/SELECT';
export const ADD_TODO = 'TODO/ADD';
export const DELETE_TODO = 'TODO/DELETE';
export const COMPLETE_TODO = 'TODO/COMPLETE';
export const UNCOMPLETE_TODO = 'TODO/UNCOMPLETE';
export const TOGGLE_TODO_CHECKED = 'TODO/TOGGLE_CHECKED';

