export const GETDATA_STARTED = 'GETDATA/STARTED';
export const GETDATA_SUCCESS = 'GETDATA/SUCCESS';
export const GETDATA_FAILURE = 'GETDATA/FAILURE';
export const UPDATE_DATA_CHECKED_STATUS = 'DATA/UPDATE_CHECKED_STATUS';
export const ADD_TODO = 'TASKLIST/ADD_TODO';

