export const CHECKUSERNAME_STARTED = 'REGIST/CHECKUSERNAME_STARTED';
export const CHECKUSERNAME_SUCCESS = 'REGIST/CHECKUSERNAME_SUCCESS';
export const CHECKUSERNAME_FAILURE = 'REGIST/CHECKUSERNAME_FAILURE';
